## 텐서플로우 상수와 함수 처리

In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

### hello world 출력

In [3]:
hello = tf.constant('Hello, tensorflow !!')

In [4]:
print(hello)

tf.Tensor(b'Hello, tensorflow !!', shape=(), dtype=string)


In [6]:
## sess = tf.Session()

In [8]:
## print(sess.run(hello))

In [9]:
## sess.close()

### 상수 계산 

In [10]:
a = tf.constant(10)

In [11]:
b = tf.constant(32)

In [12]:
c = tf.add(a,b)

In [13]:
## sess = tf.Session()

In [14]:
## print(sess.run([a,b,c]))

In [15]:
## sess.close()

In [16]:
a,b,c,

(<tf.Tensor: shape=(), dtype=int32, numpy=10>,
 <tf.Tensor: shape=(), dtype=int32, numpy=32>,
 <tf.Tensor: shape=(), dtype=int32, numpy=42>)

In [18]:
a.numpy()

10

In [19]:
b.numpy()

32

In [20]:
c.numpy()

42

### 플레이스홀더와 변수 계산

#### 플레이스 홀더 지정

In [23]:
x_data = [[1,2,3],[4,5,6]]

In [33]:
X = tf.Variable(tf.random.normal((2,3)))

#### 변수 지정 : 정규분포에 대한 임의의 값 세팅

In [34]:
W= tf.Variable(tf.random.normal((3,2)))

In [35]:
b = tf.Variable(tf.random.normal((2,1)))

In [36]:
expr = tf.matmul(X, W) + b

#### 세션 생성 

In [37]:
expr.numpy()

array([[1.6497166 , 2.394397  ],
       [0.58812684, 1.026858  ]], dtype=float32)

In [38]:
tf.random.uniform([4],0,1)

<tf.Tensor: shape=(4,), dtype=float32, numpy=array([0.28103268, 0.38539422, 0.24598193, 0.35296166], dtype=float32)>

In [39]:
tf.random.uniform([4,2],0,1).numpy()

array([[0.80333316, 0.17967582],
       [0.7481879 , 0.8621144 ],
       [0.610396  , 0.15572822],
       [0.21059942, 0.17936158]], dtype=float32)

In [40]:
tf.random.uniform([4,2,2],0,1).numpy()

array([[[0.24577701, 0.9784529 ],
        [0.9400517 , 0.875152  ]],

       [[0.6650542 , 0.4301499 ],
        [0.8916999 , 0.5700635 ]],

       [[0.5208391 , 0.91852105],
        [0.31788957, 0.99162734]],

       [[0.619154  , 0.06393576],
        [0.2373389 , 0.554598  ]]], dtype=float32)