In [1]:
import tensorflow as tf

/Users/dahlmoon/anaconda/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [12]:
tf.InteractiveSession()

In [8]:
help(tf.linspace)

Help on function lin_space in module tensorflow.python.ops.gen_math_ops:

lin_space(start, stop, num, name=None)
    Generates values in an interval.
    
    A sequence of `num` evenly-spaced values are generated beginning at `start`.
    If `num > 1`, the values in the sequence increase by `stop - start / num - 1`,
    so that the last one is exactly `stop`.
    
    For example:
    
    ```
    tf.linspace(10.0, 12.0, 3, name="linspace") => [ 10.0  11.0  12.0]
    ```
    
    Args:
      start: A `Tensor`. Must be one of the following types: `float32`, `float64`.
        First entry in the range.
      stop: A `Tensor`. Must have the same type as `start`.
        Last entry in the range.
      num: A `Tensor`. Must be one of the following types: `int32`, `int64`.
        Number of values to generate.
      name: A name for the operation (optional).
    
    Returns:
      A `Tensor`. Has the same type as `start`. 1-D. The generated values.



## 첫번째 start는 실수값을 배정해야 함

In [11]:
linear_tf = tf.linspace(start=0.,stop=1.,num=3)

In [13]:
linear_tf.eval()

array([ 0. ,  0.5,  1. ], dtype=float32)

In [16]:
linear_int = tf.linspace(start=1.,stop=3,num=3)

In [17]:
linear_int.eval()

array([ 1.,  2.,  3.], dtype=float32)

## 정수값을 처리할 때는 range  사용

In [18]:
help(tf.range)

Help on function range in module tensorflow.python.ops.math_ops:

range(start, limit=None, delta=1, dtype=None, name='range')
    Creates a sequence of numbers.
    
    Creates a sequence of numbers that begins at `start` and extends by
    increments of `delta` up to but not including `limit`.
    
    The dtype of the resulting tensor is inferred from the inputs unless
    it is provided explicitly.
    
    Like the Python builtin `range`, `start` defaults to 0, so that
    `range(n) = range(0, n)`.
    
    For example:
    
    ```python
    start = 3
    limit = 18
    delta = 3
    tf.range(start, limit, delta)  # [3, 6, 9, 12, 15]
    
    start = 3
    limit = 1
    delta = -0.5
    tf.range(start, limit, delta)  # [3, 2.5, 2, 1.5]
    
    limit = 5
    tf.range(limit)  # [0, 1, 2, 3, 4]
    ```
    
    Args:
      start: A 0-D `Tensor` (scalar). Acts as first entry in the range if
        `limit` is not None; otherwise, acts as range limit and first entry
        defaults 

In [19]:
start = 3
limit = 18
delta = 3
a = tf.range(start, limit, delta)

In [20]:
a.eval()

array([ 3,  6,  9, 12, 15], dtype=int32)

### 실수값이 필요할 경우는 delta를 소숫점 숫자로 표시

In [21]:
start = 1
limit = 2
delta = 0.5
b = tf.range(start, limit, delta)

In [22]:
b.eval()

array([ 1. ,  1.5], dtype=float32)