In [1]:
import tensorflow as tf

/Users/dahlmoon/anaconda/lib/python3.6/importlib/_bootstrap.py:205: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
tf.InteractiveSession()

## 특정 텐서의 원소를 동일한 값으로 채울 경우

In [3]:
tensor_fill = tf.fill([10,10],42)

In [4]:
tensor_fill.eval()

array([[42, 42, 42, 42, 42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42, 42, 42, 42, 42],
       [42, 42, 42, 42, 42, 42, 42, 42, 42, 42]], dtype=int32)

In [5]:
one_ = tf.ones([10,10])

In [6]:
one_.eval()

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

## 원으로 원소를 채운 텐서에 스칼라값을 42를 곱한 결과와 동일한 값이 나온다. 

In [8]:
c = one_ * 42

In [9]:
c.eval()

array([[ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.]], dtype=float32)

In [14]:
d = one_.__mul__(42)

In [15]:
one_.eval()

array([[ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.],
       [ 1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.]], dtype=float32)

In [16]:
d.eval()

array([[ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.],
       [ 42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.,  42.]], dtype=float32)

## 텐서 플로우 dtype은 변경이 불가

In [18]:
d.dtype = tf.int32

AttributeError: can't set attribute

## 특정 타입을 지정할 경우는 실제 텐서 생성할 때 타입을 dtype에 정의해야 한다

In [21]:
f = tf.ones([10,10], dtype=tf.int32)

In [22]:
f.eval()

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]], dtype=int32)