## 텐서플로우 상수와 함수 처리

In [2]:
import tensorflow as tf

In [3]:
tf.__version__

'1.13.1'

### hello world 출력

In [4]:
hello = tf.constant('Hello, tensorflow !!')

In [5]:
print(hello)

Tensor("Const:0", shape=(), dtype=string)


In [6]:
sess = tf.Session()

In [7]:
print(sess.run(hello))

b'Hello, tensorflow !!'


In [8]:
sess.close()

### 상수 계산 

In [9]:
a = tf.constant(10)

In [10]:
b = tf.constant(32)

In [11]:
c = tf.add(a,b)

In [12]:
sess = tf.Session()

In [13]:
print(sess.run([a,b,c]))

[10, 32, 42]


In [14]:
sess.close()

### 플레이스홀더와 변수 계산

#### 플레이스 홀더 지정

In [15]:
X = tf.placeholder(tf.float32, [None,3])

In [16]:
x_data = [[1,2,3],[4,5,6]]

#### 변수 지정 : 정규분포에 대한 임의의 값 세팅

In [19]:
W= tf.Variable(tf.random_normal((3,2)))

In [20]:
b = tf.Variable(tf.random_normal((2,1)))

In [21]:
expr = tf.matmul(X, W) + b

#### 세션 생성 

In [22]:
sess = tf.Session()

#### 변수 초기화 처리

In [23]:
sess.run(tf.global_variables_initializer())

#### 세션 실행

In [24]:
sess.run(W)

array([[-1.1212828 ,  0.8691779 ],
       [-0.41095665,  1.6016425 ],
       [ 0.54735327, -0.49101162]], dtype=float32)

In [25]:
sess.run(b)

array([[-0.42325503],
       [-0.14430861]], dtype=float32)

In [26]:
sess.run(expr, feed_dict={X: x_data})

array([[-0.7243913,  2.1761732],
       [-3.4001036,  8.394545 ]], dtype=float32)

In [27]:
sess.close()