In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.4.1'

In [3]:
help(tf.linspace)

Help on function linspace_nd in module tensorflow.python.ops.math_ops:

linspace_nd(start, stop, num, name=None, axis=0)
    Generates evenly-spaced values in an interval along a given axis.
    
    A sequence of `num` evenly-spaced values are generated beginning at `start`
    along a given `axis`.
    If `num > 1`, the values in the sequence increase by `stop - start / num - 1`,
    so that the last one is exactly `stop`. If `num <= 0`, `ValueError` is raised.
    
    Matches
    [np.linspace](https://docs.scipy.org/doc/numpy/reference/generated/numpy.linspace.html)'s
    behaviour
    except when `num == 0`.
    
    For example:
    
    ```
    tf.linspace(10.0, 12.0, 3, name="linspace") => [ 10.0  11.0  12.0]
    ```
    
    `Start` and `stop` can be tensors of arbitrary size:
    
    >>> tf.linspace([0., 5.], [10., 40.], 5, axis=0)
    <tf.Tensor: shape=(5, 2), dtype=float32, numpy=
    array([[ 0.  ,  5.  ],
           [ 2.5 , 13.75],
           [ 5.  , 22.5 ],
           [

## 첫번째 start는 실수값을 배정해야 함

In [4]:
linear_tf = tf.linspace(start=0.,stop=1.,num=3)

In [5]:
linear_tf

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([0. , 0.5, 1. ], dtype=float32)>

In [6]:
linear_int = tf.linspace(start=1.,stop=3,num=3)

In [7]:
linear_int

<tf.Tensor: shape=(3,), dtype=float32, numpy=array([1., 2., 3.], dtype=float32)>

## 정수값을 처리할 때는 range  사용

In [8]:
help(tf.range)

Help on function range in module tensorflow.python.ops.math_ops:

range(start, limit=None, delta=1, dtype=None, name='range')
    Creates a sequence of numbers.
    
    Creates a sequence of numbers that begins at `start` and extends by
    increments of `delta` up to but not including `limit`.
    
    The dtype of the resulting tensor is inferred from the inputs unless
    it is provided explicitly.
    
    Like the Python builtin `range`, `start` defaults to 0, so that
    `range(n) = range(0, n)`.
    
    For example:
    
    >>> start = 3
    >>> limit = 18
    >>> delta = 3
    >>> tf.range(start, limit, delta)
    <tf.Tensor: shape=(5,), dtype=int32,
    numpy=array([ 3,  6,  9, 12, 15], dtype=int32)>
    
    >>> start = 3
    >>> limit = 1
    >>> delta = -0.5
    >>> tf.range(start, limit, delta)
    <tf.Tensor: shape=(4,), dtype=float32,
    numpy=array([3. , 2.5, 2. , 1.5], dtype=float32)>
    
    >>> limit = 5
    >>> tf.range(limit)
    <tf.Tensor: shape=(5,), dtype=

In [9]:
start = 3
limit = 18
delta = 3
a = tf.range(start, limit, delta)

In [10]:
a

<tf.Tensor: shape=(5,), dtype=int32, numpy=array([ 3,  6,  9, 12, 15], dtype=int32)>

### 실수값이 필요할 경우는 delta를 소숫점 숫자로 표시

In [11]:
start = 1
limit = 2
delta = 0.5
b = tf.range(start, limit, delta)

In [12]:
b

<tf.Tensor: shape=(2,), dtype=float32, numpy=array([1. , 1.5], dtype=float32)>