In [1]:
import tensorflow as tf

In [2]:
tf.__version__

'2.0.0'

In [3]:
for i in dir(tf) :
    if i.startswith('rand') :
        print(i)

random
random_normal_initializer
random_uniform_initializer


In [4]:
import keras

Using TensorFlow backend.


In [5]:
keras.__version__

'2.3.1'

In [33]:
tf.keras.__version__

'2.2.4-tf'

## 정규분포의 값을 가지고 생성하기

In [6]:
dir(tf.random)

['__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'all_candidate_sampler',
 'categorical',
 'experimental',
 'fixed_unigram_candidate_sampler',
 'gamma',
 'learned_unigram_candidate_sampler',
 'log_uniform_candidate_sampler',
 'normal',
 'poisson',
 'set_seed',
 'shuffle',
 'stateless_categorical',
 'stateless_normal',
 'stateless_truncated_normal',
 'stateless_uniform',
 'truncated_normal',
 'uniform',
 'uniform_candidate_sampler']

In [7]:
import numpy as np

## 정규분포 처리 

In [8]:
s = np.random.seed(100)

In [9]:
help(tf.random.normal)

Help on function random_normal in module tensorflow.python.ops.random_ops:

random_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
    Outputs random values from a normal distribution.
    
    Args:
      shape: A 1-D integer Tensor or Python array. The shape of the output tensor.
      mean: A 0-D Tensor or Python value of type `dtype`. The mean of the normal
        distribution.
      stddev: A 0-D Tensor or Python value of type `dtype`. The standard deviation
        of the normal distribution.
      dtype: The type of the output.
      seed: A Python integer. Used to create a random seed for the distribution.
        See
        `tf.compat.v1.set_random_seed`
        for behavior.
      name: A name for the operation (optional).
    
    Returns:
      A tensor of the specified shape filled with random normal values.



In [10]:
a = tf.random.normal([3,3], seed=s)

In [11]:
a

<tf.Tensor: id=5, shape=(3, 3), dtype=float32, numpy=
array([[-0.27324325,  0.27934757, -1.368191  ],
       [-0.01408654, -3.2095647 , -0.27149737],
       [ 0.86494255, -1.5196658 , -1.684768  ]], dtype=float32)>

In [12]:
np.random.RandomState(s) 
np.random.normal(size=(3,3))

array([[-1.74976547,  0.3426804 ,  1.1530358 ],
       [-0.25243604,  0.98132079,  0.51421884],
       [ 0.22117967, -1.07004333, -0.18949583]])

## 균등분포의 값을 가지고 생성하기

In [13]:
help(tf.random.uniform)

Help on function random_uniform in module tensorflow.python.ops.random_ops:

random_uniform(shape, minval=0, maxval=None, dtype=tf.float32, seed=None, name=None)
    Outputs random values from a uniform distribution.
    
    The generated values follow a uniform distribution in the range
    `[minval, maxval)`. The lower bound `minval` is included in the range, while
    the upper bound `maxval` is excluded.
    
    For floats, the default range is `[0, 1)`.  For ints, at least `maxval` must
    be specified explicitly.
    
    In the integer case, the random integers are slightly biased unless
    `maxval - minval` is an exact power of two.  The bias is small for values of
    `maxval - minval` significantly smaller than the range of the output (either
    `2**32` or `2**64`).
    
    Args:
      shape: A 1-D integer Tensor or Python array. The shape of the output tensor.
      minval: A 0-D Tensor or Python value of type `dtype`. The lower bound on the
        range of random val

In [14]:
b = tf.random.uniform([3,3])

In [15]:
b

<tf.Tensor: id=12, shape=(3, 3), dtype=float32, numpy=
array([[0.7437413 , 0.23504388, 0.53814673],
       [0.6087197 , 0.80641544, 0.65513694],
       [0.9919858 , 0.96912897, 0.41468072]], dtype=float32)>

In [16]:
b = tf.random.uniform([3,3], 0, 10)

In [17]:
b

<tf.Tensor: id=19, shape=(3, 3), dtype=float32, numpy=
array([[7.8668556, 2.8419209, 8.482273 ],
       [3.2865894, 9.025097 , 3.1836355],
       [2.3452103, 1.0929847, 3.6969137]], dtype=float32)>

### 균등분포를 정수로 처리하기

In [18]:
b = tf.random.uniform([3,3], 0, 10,tf.int32)

In [19]:
b

<tf.Tensor: id=23, shape=(3, 3), dtype=int32, numpy=
array([[7, 6, 9],
       [4, 0, 9],
       [2, 2, 5]], dtype=int32)>

## 특정 범위를 가지고 정규분포를 처리하기

In [20]:
help(tf.random.truncated_normal)

Help on function truncated_normal in module tensorflow.python.ops.random_ops:

truncated_normal(shape, mean=0.0, stddev=1.0, dtype=tf.float32, seed=None, name=None)
    Outputs random values from a truncated normal distribution.
    
    The generated values follow a normal distribution with specified mean and
    standard deviation, except that values whose magnitude is more than 2 standard
    deviations from the mean are dropped and re-picked.
    
    Args:
      shape: A 1-D integer Tensor or Python array. The shape of the output tensor.
      mean: A 0-D Tensor or Python value of type `dtype`. The mean of the
        truncated normal distribution.
      stddev: A 0-D Tensor or Python value of type `dtype`. The standard deviation
        of the normal distribution, before truncation.
      dtype: The type of the output.
      seed: A Python integer. Used to create a random seed for the distribution.
        See
        `tf.compat.v1.set_random_seed`
        for behavior.
      nam

In [21]:
t = tf.random.truncated_normal([3,3])

In [22]:
t

<tf.Tensor: id=29, shape=(3, 3), dtype=float32, numpy=
array([[ 0.420243  ,  0.6115547 , -1.6160558 ],
       [ 0.9773476 , -1.3709598 , -0.06733866],
       [-0.699689  , -0.18919781, -0.35916522]], dtype=float32)>

## 내부의 원소를 섞기

In [23]:
help(tf.random.shuffle)

Help on function random_shuffle in module tensorflow.python.ops.random_ops:

random_shuffle(value, seed=None, name=None)
    Randomly shuffles a tensor along its first dimension.
    
    The tensor is shuffled along dimension 0, such that each `value[j]` is mapped
    to one and only one `output[i]`. For example, a mapping that might occur for a
    3x2 tensor is:
    
    ```python
    [[1, 2],       [[5, 6],
     [3, 4],  ==>   [1, 2],
     [5, 6]]        [3, 4]]
    ```
    
    Args:
      value: A Tensor to be shuffled.
      seed: A Python integer. Used to create a random seed for the distribution.
        See
        `tf.compat.v1.set_random_seed`
        for behavior.
      name: A name for the operation (optional).
    
    Returns:
      A tensor of same shape and type as `value`, shuffled along its first
      dimension.



In [24]:
s = tf.random.shuffle([1,2,3,4])

In [25]:
s

<tf.Tensor: id=31, shape=(4,), dtype=int32, numpy=array([1, 2, 4, 3], dtype=int32)>

## 텐서의 결과를 특정 값으로 분리해서 다시 생성하기

In [26]:
import tensorflow_core.compat.v1 as tf

In [27]:
 tf.random_crop

<function tensorflow.python.ops.random_ops.random_crop(value, size, seed=None, name=None)>

In [28]:
tf.InteractiveSession()

In [29]:
d = tf.random_crop(tf.random_uniform([3,3,3]),[2,2,2])

In [30]:
d.numpy()

array([[[0.96284544, 0.12575996],
        [0.5426768 , 0.6771921 ]],

       [[0.22155023, 0.16560638],
        [0.16745842, 0.49607038]]], dtype=float32)

In [31]:
d.shape

TensorShape([2, 2, 2])