## 코랩  처리

https://colab.research.google.com/drive/1UCJt8EYjlzCs1H1d1X0iDGYJsHKwu-NO?fbclid=IwAR31f-mtcrc3TnVZcyyvD4zmAJR74rB7pkBENDRyxHVbaaV5e0ycnO20ln8

## 코랩 한글버전

https://colab.research.google.com/drive/1p4RhSj1FEuscyZP81ocn8IeGD_2r46fS?fbclid=IwAR1mCEdSUqMiivQGuPuFzjk2U_WyhBA2sUpkluA2EF_E6YKSJMoZi-bmfzA

##  코랩 기초 알아보기

https://colab.research.google.com/notebooks/welcome.ipynb?fbclid=IwAR14XBskxIw3vbDVO309gNhrtUzrAheYToffh6Cll9K1g9XAEz4LgVHLALA

In [1]:
import tensorflow 

In [2]:
tensorflow .__version__

'2.0.0'

In [3]:
import tensorflow as tf

In [4]:
dir(tf)

['AggregationMethod',
 'Assert',
 'CriticalSection',
 'DType',
 'DeviceSpec',
 'GradientTape',
 'Graph',
 'IndexedSlices',
 'IndexedSlicesSpec',
 'Module',
 'Operation',
 'OptionalSpec',
 'RaggedTensor',
 'RaggedTensorSpec',
 'RegisterGradient',
 'SparseTensor',
 'SparseTensorSpec',
 'Tensor',
 'TensorArray',
 'TensorArraySpec',
 'TensorShape',
 'TensorSpec',
 'TypeSpec',
 'UnconnectedGradients',
 'Variable',
 'VariableAggregation',
 'VariableSynchronization',
 '_LazyLoader',
 '__builtins__',
 '__cached__',
 '__compiler_version__',
 '__cxx11_abi_flag__',
 '__doc__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__monolithic_build__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_absolute_import',
 '_api',
 '_division',
 '_forward_module',
 '_importlib',
 '_m',
 '_print_function',
 '_root_estimator',
 '_sys',
 '_top_level_modules',
 '_types',
 'abs',
 'acos',
 'acosh',
 'add',
 'add_n',
 'argmax',
 'argmin',
 'argsort',
 'as_dtype',
 'as_string',
 'asin',

In [5]:
import tensorflow as tf

hello = tf.constant("Hello")
# sess = tf.Session()
#print(sess.run(hello))

tf.print(hello)

Hello


In [68]:
hello.numpy()

b'Hello'

In [12]:
import numpy as np

In [15]:
def f(x, y):
    return tf.reduce_mean(tf.multiply(x ** 2, 3) + y)

def g(x,y) :
    return np.mean(np.multiply(x**2, 3) +y)

#g = tf.function(f)

x = tf.constant([[2.0, 3.0]])
y = tf.constant([[3.0, -2.0]])

# `f` and `g` will return the same value, but `g` will be executed as a
# TensorFlow graph.
assert f(x, y).numpy() == g(x, y)

print(f(x,y).numpy())
print(g(x,y))

20.0
20.0


In [7]:
x = tf.constant([[5, 2], [1, 3]])
print(x)

tf.Tensor(
[[5 2]
 [1 3]], shape=(2, 2), dtype=int32)


In [10]:
x.numpy() * 3

array([[15,  6],
       [ 3,  9]], dtype=int32)

In [9]:
tf.print(x)

[[5 2]
 [1 3]]


In [11]:
x * 3

<tf.Tensor: id=35, shape=(2, 2), dtype=int32, numpy=
array([[15,  6],
       [ 3,  9]], dtype=int32)>

In [29]:
import numpy as np
@tf.function
def intersection(rect1, rect2):
    print('intersection==================================')
    top = tf.math.maximum(rect1[1], rect2[1])
    left = tf.math.maximum(rect1[0], rect2[0])
    right = tf.math.minimum(rect1[0] + rect1[2], rect2[0] + rect2[2])
    bottom = tf.math.minimum(rect1[1] + rect1[3], rect2[1] + rect2[3])

    result = tf.where(tf.math.logical_and(tf.greater(bottom, top), tf.greater(right, left)), (bottom-top)*(right-left), 0)

    return result

In [30]:
@tf.function
def jaccard(rect1, rect2):
    # len_rect1_ : 4, len_rect2_ : 4
    rect1_ = []
    for i in range(len(rect1)):
        cond_value = tf.where(rect1[i] >= 0, rect1[i], 0)
        rect1_.append(cond_value)
            
    rect2_ = []
    for i in range(len(rect2)):
        cond_value = tf.where(rect2[i] >= 0, rect2[i], 0)
        rect2_.append(cond_value)
    
    s = tf.add(tf.multiply(rect1_[2], rect1_[3]), tf.multiply(rect2_[2], rect2_[3]))

    # rect1 and rect2 => A∧B
    intersect = intersection(rect1_, rect2_)

    # rect1 or rect2 => A∨B
    union = s - intersect

    # A∧B / A∨B
    return tf.divide(intersect, union)

In [47]:
a = tf.constant(0)

In [48]:
a.numpy()

0

In [74]:
a = a + 1

In [75]:
a.numpy()

1

In [98]:

#@tf.function
def test():
    number = tf.constant(1)
    print(number.numpy())
  
    jacc = jaccard([10, 10, 10, 10], [20, 20, 20, 20])
    #print(number)
  
    for i in range(10):
#  이 부분에 의해서 int였던 number가 Tensor 형태로 바뀝니다.
            number= tf.add(number,1)

    print((number).numpy()) # Tensor("mul:0", shape=(), dtype=int32)


In [99]:
test()

1
11


In [41]:
dir(tf)

['AggregationMethod',
 'Assert',
 'CriticalSection',
 'DType',
 'DeviceSpec',
 'GradientTape',
 'Graph',
 'IndexedSlices',
 'IndexedSlicesSpec',
 'Module',
 'Operation',
 'OptionalSpec',
 'RaggedTensor',
 'RaggedTensorSpec',
 'RegisterGradient',
 'SparseTensor',
 'SparseTensorSpec',
 'Tensor',
 'TensorArray',
 'TensorArraySpec',
 'TensorShape',
 'TensorSpec',
 'TypeSpec',
 'UnconnectedGradients',
 'Variable',
 'VariableAggregation',
 'VariableSynchronization',
 '_LazyLoader',
 '__builtins__',
 '__cached__',
 '__compiler_version__',
 '__cxx11_abi_flag__',
 '__doc__',
 '__file__',
 '__git_version__',
 '__loader__',
 '__monolithic_build__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '__version__',
 '_absolute_import',
 '_api',
 '_division',
 '_forward_module',
 '_importlib',
 '_m',
 '_print_function',
 '_root_estimator',
 '_sys',
 '_top_level_modules',
 '_types',
 'abs',
 'acos',
 'acosh',
 'add',
 'add_n',
 'argmax',
 'argmin',
 'argsort',
 'as_dtype',
 'as_string',
 'asin',