In [1]:
import tensorflow as tf

W1012 19:49:40.636920 17324 __init__.py:321] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W1012 19:49:40.703772 17324 __init__.py:321] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W1012 19:49:40.741674 17324 __init__.py:352] Limited tf.summary API due to missing TensorBoard installation.


In [2]:
tf.__version__

'2.0.0'

# 1. 선형대수 모듈

##

https://www.tensorflow.org/api_docs/python/tf/linalg

In [73]:
dir(tf.linalg)

['LinearOperator',
 'LinearOperatorAdjoint',
 'LinearOperatorBlockDiag',
 'LinearOperatorCirculant',
 'LinearOperatorCirculant2D',
 'LinearOperatorCirculant3D',
 'LinearOperatorComposition',
 'LinearOperatorDiag',
 'LinearOperatorFullMatrix',
 'LinearOperatorHouseholder',
 'LinearOperatorIdentity',
 'LinearOperatorInversion',
 'LinearOperatorKronecker',
 'LinearOperatorLowRankUpdate',
 'LinearOperatorLowerTriangular',
 'LinearOperatorScaledIdentity',
 'LinearOperatorToeplitz',
 'LinearOperatorZeros',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'adjoint',
 'band_part',
 'cholesky',
 'cholesky_solve',
 'cross',
 'det',
 'diag',
 'diag_part',
 'eigh',
 'eigvalsh',
 'einsum',
 'expm',
 'eye',
 'global_norm',
 'inv',
 'l2_normalize',
 'logdet',
 'logm',
 'lstsq',
 'lu',
 'matmul',
 'matrix_transpose',
 'matvec',
 'norm',
 'normalize',
 'qr',
 'set_diag',
 'slogdet',
 'solve',
 'sqrtm',
 'svd',
 'ten

In [4]:
tf.matmul

<function tensorflow.python.ops.math_ops.matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)>

In [6]:
tf.matrix_square_root

<function tensorflow.python.ops.gen_linalg_ops.matrix_square_root(input, name=None)>

In [14]:
rank2_tensor = tf.ones([3, 3], name='MatrixA')

In [15]:
rank2_tensor

<tf.Tensor: id=8, shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
rank2_tensor.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [17]:
rank2_tensor_ = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], name='MatrixB', dtype=tf.float32)

In [18]:
rank2_tensor_

<tf.Tensor: id=9, shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [19]:
rank2_tensor_.numpy()

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [22]:
tf.add(rank2_tensor, rank2_tensor_, name='MatrixC')

<tf.Tensor: id=10, shape=(3, 3), dtype=float32, numpy=
array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]], dtype=float32)>

## 계산을 바로 확인할 수 있다. 

In [23]:
# Create scalar a, c and Matrix B
rank_0_tensor_a = tf.constant(2, name="scalar_a", dtype=tf.float32)
rank_2_tensor_B = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], name='MatrixB', dtype=tf.float32)
rank_0_tensor_c = tf.constant(3, name="scalar_c", dtype=tf.float32)

# multiplying aB
multiply_scalar = tf.multiply(rank_0_tensor_a, rank_2_tensor_B)
# adding aB + c
rank_2_tensor_D = tf.add(multiply_scalar, rank_0_tensor_c, name="MatrixD")

In [24]:
rank_2_tensor_D

<tf.Tensor: id=15, shape=(3, 3), dtype=float32, numpy=
array([[ 5.,  7.,  9.],
       [11., 13., 15.],
       [17., 19., 21.]], dtype=float32)>

## 행렬의 연산

In [32]:
rank_1_tensor_b = tf.constant([[4.], [5.], [6.]])

In [35]:
rank_1_tensor_b

<tf.Tensor: id=22, shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [6.]], dtype=float32)>

In [33]:
# Broadcasting a vector b to a matrix A such that it yields a matrix F = A + b
rank_2_tensor_F = tf.add(rank_2_tensor_A, rank_1_tensor_b, name="broadcastF")

In [34]:
rank_2_tensor_F

<tf.Tensor: id=23, shape=(3, 3), dtype=float32, numpy=
array([[5., 5., 5.],
       [6., 6., 6.],
       [7., 7., 7.]], dtype=float32)>

## 전치행렬

In [27]:
# Creating a Matrix E
rank_2_tensor_E = tf.constant([[1, 2, 3], [4, 5, 6]])

In [28]:
rank_2_tensor_E

<tf.Tensor: id=19, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [29]:
# Transposing Matrix E
transpose_E = tf.transpose(rank_2_tensor_E, name="transposeE")

In [30]:
transpose_E

<tf.Tensor: id=21, shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>

## 고유값 분해 

In [36]:
# Let's see how we can compute the eigen vectors and values from a matrix
e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

In [61]:
e_matrix_A

<tf.Tensor: id=30, shape=(2, 2), dtype=float32, numpy=
array([[7.752946 , 4.436414 ],
       [7.9676538, 7.9100547]], dtype=float32)>

In [37]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh
eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

In [38]:
eigen_values_A

<tf.Tensor: id=31, shape=(2,), dtype=float32, numpy=array([-0.1365406, 15.7995405], dtype=float32)>

In [39]:
eigen_vectors_A

<tf.Tensor: id=32, shape=(2, 2), dtype=float32, numpy=
array([[-0.71058387, -0.7036125 ],
       [ 0.7036125 , -0.71058387]], dtype=float32)>

In [52]:
import numpy as np

In [53]:
eye = np.eye(2)

In [62]:
AA = eigen_values_A.numpy() * eye 

In [66]:
AA

array([[-0.13654061,  0.        ],
       [-0.        , 15.79954052]])

In [63]:
BB = np.dot(eigen_vectors_A, AA )

In [67]:
BB

array([[  0.09702355, -11.1167543 ],
       [ -0.09607168, -11.22689858]])

In [68]:
np.linalg.inv(eigen_vectors_A.numpy())

array([[-0.71058387,  0.7036125 ],
       [-0.7036125 , -0.71058387]], dtype=float32)

In [64]:
CC = np.dot( BB, np.linalg.inv(eigen_vectors_A.numpy()))

In [65]:
CC

array([[7.75294399, 7.96765323],
       [7.96765323, 7.91005576]])

In [74]:
new_matrix_A = tf.Variable(tf.random.uniform([2,2], minval=1, maxval=10, dtype=tf.float32))

In [75]:
new_matrix_A

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[1.257417 , 8.92877  ],
       [9.600967 , 7.2714777]], dtype=float32)>

In [ ]:
tf.linalg.eigh(new_matrix_A)

### 대칭 행렬 만들기

In [76]:
X_upper = tf.linalg.band_part(new_matrix_A, 0, -1)

In [77]:
X_upper

<tf.Tensor: id=122, shape=(2, 2), dtype=float32, numpy=
array([[1.257417 , 8.92877  ],
       [0.       , 7.2714777]], dtype=float32)>

In [83]:
(X_upper + tf.transpose(X_upper))

<tf.Tensor: id=132, shape=(2, 2), dtype=float32, numpy=
array([[ 2.514834,  8.92877 ],
       [ 8.92877 , 14.542955]], dtype=float32)>

In [84]:
0.5*(X_upper + tf.transpose(X_upper))

<tf.Tensor: id=137, shape=(2, 2), dtype=float32, numpy=
array([[1.257417 , 4.464385 ],
       [4.464385 , 7.2714777]], dtype=float32)>

In [85]:
sym_matrix_A = tf.multiply(0.5, (X_upper + tf.transpose(X_upper)))

In [86]:
sym_matrix_A

<tf.Tensor: id=142, shape=(2, 2), dtype=float32, numpy=
array([[1.257417 , 4.464385 ],
       [4.464385 , 7.2714777]], dtype=float32)>

In [79]:
# create orthogonal matrix Q from eigen vectors of A
eigen_values_Q, eigen_vectors_Q = tf.linalg.eigh(sym_matrix_A)

In [80]:
eigen_values_Q

<tf.Tensor: id=128, shape=(2,), dtype=float32, numpy=array([-1.1182066,  9.6471   ], dtype=float32)>

In [81]:
eigen_vectors_Q

<tf.Tensor: id=129, shape=(2, 2), dtype=float32, numpy=
array([[-0.8827944, -0.4697595],
       [ 0.4697595, -0.8827944]], dtype=float32)>

## 차이 생김 

In [87]:
tf.linalg.eigh(new_matrix_A)

(<tf.Tensor: id=144, shape=(2,), dtype=float32, numpy=array([-5.796408, 14.325304], dtype=float32)>,
 <tf.Tensor: id=145, shape=(2, 2), dtype=float32, numpy=
 array([[-0.8058797 , -0.59207934],
        [ 0.59207934, -0.8058797 ]], dtype=float32)>)

In [46]:
Av = tf.tensordot(e_matrix_A, eigen_vectors_A, axes=0)

In [42]:
Av

<tf.Tensor: id=43, shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[-5.509118 , -5.4550695],
         [ 5.4550695, -5.509118 ]],

        [[-3.1524441, -3.1215162],
         [ 3.1215162, -3.1524441]]],


       [[[-5.6616864, -5.6061406],
         [ 5.6061406, -5.6616864]],

        [[-5.620757 , -5.5656133],
         [ 5.5656133, -5.620757 ]]]], dtype=float32)>

In [47]:
sv = tf.multiply(5, eigen_vectors_A)

In [48]:
sv

<tf.Tensor: id=78, shape=(2, 2), dtype=float32, numpy=
array([[-3.5529194, -3.5180626],
       [ 3.5180626, -3.5529194]], dtype=float32)>