In [1]:
import tensorflow as tf

W1012 20:47:37.819988 16400 __init__.py:321] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W1012 20:47:37.889801 16400 __init__.py:321] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W1012 20:47:37.927732 16400 __init__.py:352] Limited tf.summary API due to missing TensorBoard installation.


In [2]:
tf.__version__

'2.0.0'

# 1. 고유값 분해

##

https://www.tensorflow.org/api_docs/python/tf/linalg

## 고유값 분해 

In [3]:
# Let's see how we can compute the eigen vectors and values from a matrix
e_matrix_A = tf.random.uniform([2, 2], minval=3, maxval=10, dtype=tf.float32, name="matrixA")

In [4]:
e_matrix_A

<tf.Tensor: id=6, shape=(2, 2), dtype=float32, numpy=
array([[7.6101875, 5.497458 ],
       [3.417417 , 3.9004846]], dtype=float32)>

In [5]:
# Calculating the eigen values and vectors using tf.linalg.eigh, if you only want the values you can use eigvalsh
eigen_values_A, eigen_vectors_A = tf.linalg.eigh(e_matrix_A)

In [6]:
eigen_values_A

<tf.Tensor: id=7, shape=(2,), dtype=float32, numpy=array([1.8669928, 9.64368  ], dtype=float32)>

In [7]:
eigen_vectors_A

<tf.Tensor: id=8, shape=(2, 2), dtype=float32, numpy=
array([[-0.51135665,  0.8593686 ],
       [ 0.8593686 ,  0.51135665]], dtype=float32)>

In [8]:
import numpy as np

In [9]:
eye = np.eye(2)

In [10]:
AA = eigen_values_A.numpy() * eye 

In [11]:
AA

array([[1.86699283, 0.        ],
       [0.        , 9.64367962]])

In [12]:
BB = np.dot(eigen_vectors_A, AA )

In [13]:
BB

array([[-0.9546992 ,  8.28747567],
       [ 1.60443506,  4.93135972]])

In [14]:
np.linalg.inv(eigen_vectors_A.numpy())

array([[-0.51135665,  0.85936856],
       [ 0.85936856,  0.51135665]], dtype=float32)

In [15]:
CC = np.dot( BB, np.linalg.inv(eigen_vectors_A.numpy()))

In [16]:
CC

array([[7.61018784, 3.41741733],
       [3.41741698, 3.90048464]])

In [17]:
new_matrix_A = tf.Variable(tf.random.uniform([2,2], minval=1, maxval=10, dtype=tf.float32))

In [18]:
new_matrix_A

<tf.Variable 'Variable:0' shape=(2, 2) dtype=float32, numpy=
array([[6.8172846, 8.29133  ],
       [9.815156 , 8.765879 ]], dtype=float32)>

In [19]:
tf.linalg.eigh(new_matrix_A)

(<tf.Tensor: id=25, shape=(2,), dtype=float32, numpy=array([-2.0718129, 17.654978 ], dtype=float32)>,
 <tf.Tensor: id=26, shape=(2, 2), dtype=float32, numpy=
 array([[-0.7412082, -0.6712753],
        [ 0.6712753, -0.7412082]], dtype=float32)>)

### 대칭 행렬 만들기

In [20]:
X_upper = tf.linalg.band_part(new_matrix_A, 0, -1)

In [21]:
X_upper

<tf.Tensor: id=30, shape=(2, 2), dtype=float32, numpy=
array([[6.8172846, 8.29133  ],
       [0.       , 8.765879 ]], dtype=float32)>

In [22]:
(X_upper + tf.transpose(X_upper))

<tf.Tensor: id=33, shape=(2, 2), dtype=float32, numpy=
array([[13.634569,  8.29133 ],
       [ 8.29133 , 17.531757]], dtype=float32)>

In [23]:
0.5*(X_upper + tf.transpose(X_upper))

<tf.Tensor: id=38, shape=(2, 2), dtype=float32, numpy=
array([[6.8172846, 4.145665 ],
       [4.145665 , 8.765879 ]], dtype=float32)>

In [24]:
sym_matrix_A = tf.multiply(0.5, (X_upper + tf.transpose(X_upper)))

In [25]:
sym_matrix_A

<tf.Tensor: id=43, shape=(2, 2), dtype=float32, numpy=
array([[6.8172846, 4.145665 ],
       [4.145665 , 8.765879 ]], dtype=float32)>

In [26]:
# create orthogonal matrix Q from eigen vectors of A
eigen_values_Q, eigen_vectors_Q = tf.linalg.eigh(sym_matrix_A)

In [27]:
eigen_values_Q

<tf.Tensor: id=44, shape=(2,), dtype=float32, numpy=array([ 3.532968, 12.050197], dtype=float32)>

In [28]:
eigen_vectors_Q

<tf.Tensor: id=45, shape=(2, 2), dtype=float32, numpy=
array([[-0.78383124, -0.620974  ],
       [ 0.620974  , -0.78383124]], dtype=float32)>

## 차이 생김 

In [29]:
tf.linalg.eigh(new_matrix_A)

(<tf.Tensor: id=47, shape=(2,), dtype=float32, numpy=array([-2.0718129, 17.654978 ], dtype=float32)>,
 <tf.Tensor: id=48, shape=(2, 2), dtype=float32, numpy=
 array([[-0.7412082, -0.6712753],
        [ 0.6712753, -0.7412082]], dtype=float32)>)

In [30]:
Av = tf.tensordot(e_matrix_A, eigen_vectors_A, axes=0)

In [31]:
Av

<tf.Tensor: id=59, shape=(2, 2, 2, 2), dtype=float32, numpy=
array([[[[-3.89152  ,  6.5399566],
         [ 6.5399566,  3.89152  ]],

        [[-2.8111618,  4.724343 ],
         [ 4.724343 ,  2.8111618]]],


       [[[-1.7475189,  2.936821 ],
         [ 2.936821 ,  1.7475189]],

        [[-1.9945388,  3.351954 ],
         [ 3.351954 ,  1.9945388]]]], dtype=float32)>

In [32]:
sv = tf.multiply(5, eigen_vectors_A)

In [33]:
sv

<tf.Tensor: id=61, shape=(2, 2), dtype=float32, numpy=
array([[-2.5567832,  4.296843 ],
       [ 4.296843 ,  2.5567832]], dtype=float32)>