In [1]:
import tensorflow as tf

W1012 19:49:40.636920 17324 __init__.py:321] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W1012 19:49:40.703772 17324 __init__.py:321] Limited tf.compat.v2.summary API due to missing TensorBoard installation.
W1012 19:49:40.741674 17324 __init__.py:352] Limited tf.summary API due to missing TensorBoard installation.


In [2]:
tf.__version__

'2.0.0'

# 1. 선형대수 모듈

##

https://www.tensorflow.org/api_docs/python/tf/linalg

In [73]:
dir(tf.linalg)

['LinearOperator',
 'LinearOperatorAdjoint',
 'LinearOperatorBlockDiag',
 'LinearOperatorCirculant',
 'LinearOperatorCirculant2D',
 'LinearOperatorCirculant3D',
 'LinearOperatorComposition',
 'LinearOperatorDiag',
 'LinearOperatorFullMatrix',
 'LinearOperatorHouseholder',
 'LinearOperatorIdentity',
 'LinearOperatorInversion',
 'LinearOperatorKronecker',
 'LinearOperatorLowRankUpdate',
 'LinearOperatorLowerTriangular',
 'LinearOperatorScaledIdentity',
 'LinearOperatorToeplitz',
 'LinearOperatorZeros',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_sys',
 'adjoint',
 'band_part',
 'cholesky',
 'cholesky_solve',
 'cross',
 'det',
 'diag',
 'diag_part',
 'eigh',
 'eigvalsh',
 'einsum',
 'expm',
 'eye',
 'global_norm',
 'inv',
 'l2_normalize',
 'logdet',
 'logm',
 'lstsq',
 'lu',
 'matmul',
 'matrix_transpose',
 'matvec',
 'norm',
 'normalize',
 'qr',
 'set_diag',
 'slogdet',
 'solve',
 'sqrtm',
 'svd',
 'ten

In [4]:
tf.matmul

<function tensorflow.python.ops.math_ops.matmul(a, b, transpose_a=False, transpose_b=False, adjoint_a=False, adjoint_b=False, a_is_sparse=False, b_is_sparse=False, name=None)>

In [6]:
tf.matrix_square_root

<function tensorflow.python.ops.gen_linalg_ops.matrix_square_root(input, name=None)>

In [14]:
rank2_tensor = tf.ones([3, 3], name='MatrixA')

In [15]:
rank2_tensor

<tf.Tensor: id=8, shape=(3, 3), dtype=float32, numpy=
array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)>

In [16]:
rank2_tensor.numpy()

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]], dtype=float32)

In [17]:
rank2_tensor_ = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], name='MatrixB', dtype=tf.float32)

In [18]:
rank2_tensor_

<tf.Tensor: id=9, shape=(3, 3), dtype=float32, numpy=
array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)>

In [19]:
rank2_tensor_.numpy()

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]], dtype=float32)

In [22]:
tf.add(rank2_tensor, rank2_tensor_, name='MatrixC')

<tf.Tensor: id=10, shape=(3, 3), dtype=float32, numpy=
array([[ 2.,  3.,  4.],
       [ 5.,  6.,  7.],
       [ 8.,  9., 10.]], dtype=float32)>

## 계산을 바로 확인할 수 있다. 

In [23]:
# Create scalar a, c and Matrix B
rank_0_tensor_a = tf.constant(2, name="scalar_a", dtype=tf.float32)
rank_2_tensor_B = tf.constant([[1, 2, 3], [4, 5, 6], [7, 8, 9]], name='MatrixB', dtype=tf.float32)
rank_0_tensor_c = tf.constant(3, name="scalar_c", dtype=tf.float32)

# multiplying aB
multiply_scalar = tf.multiply(rank_0_tensor_a, rank_2_tensor_B)
# adding aB + c
rank_2_tensor_D = tf.add(multiply_scalar, rank_0_tensor_c, name="MatrixD")

In [24]:
rank_2_tensor_D

<tf.Tensor: id=15, shape=(3, 3), dtype=float32, numpy=
array([[ 5.,  7.,  9.],
       [11., 13., 15.],
       [17., 19., 21.]], dtype=float32)>

## 행렬의 연산

In [32]:
rank_1_tensor_b = tf.constant([[4.], [5.], [6.]])

In [35]:
rank_1_tensor_b

<tf.Tensor: id=22, shape=(3, 1), dtype=float32, numpy=
array([[4.],
       [5.],
       [6.]], dtype=float32)>

In [33]:
# Broadcasting a vector b to a matrix A such that it yields a matrix F = A + b
rank_2_tensor_F = tf.add(rank_2_tensor_A, rank_1_tensor_b, name="broadcastF")

In [34]:
rank_2_tensor_F

<tf.Tensor: id=23, shape=(3, 3), dtype=float32, numpy=
array([[5., 5., 5.],
       [6., 6., 6.],
       [7., 7., 7.]], dtype=float32)>

## 전치행렬

In [27]:
# Creating a Matrix E
rank_2_tensor_E = tf.constant([[1, 2, 3], [4, 5, 6]])

In [28]:
rank_2_tensor_E

<tf.Tensor: id=19, shape=(2, 3), dtype=int32, numpy=
array([[1, 2, 3],
       [4, 5, 6]])>

In [29]:
# Transposing Matrix E
transpose_E = tf.transpose(rank_2_tensor_E, name="transposeE")

In [30]:
transpose_E

<tf.Tensor: id=21, shape=(3, 2), dtype=int32, numpy=
array([[1, 4],
       [2, 5],
       [3, 6]])>